print("\t Автодиллер")
print("Введите стоимость машины:")
car = int(input())
tax = int(car * 0.05)
dues = int(car * 0.02)
agency = int(10000)
delivery = int(5000)
print("\nСейчас мы посчитаем ее соимость с наценками:\n")
print("1)Налаог на машину:", int(car * 0.05), "руб")
print("2)Регистрационный сбор:", int(car * 0.02), "руб")
print("3)Агентские сборы:", int(10000), "руб")
print("4)Доставка машины:", int(5000), "руб")
total = car + tax + dues + agency + delivery
print("\nОкончательная цена машины:", int(total), "руб")
